### ISSUE TITLE
Is it possible to load all packages and display all warnings

### ISSUE THREAD

**Issue by tungmilan** [trinker/pacman#103]
Hello,

I really like the convenient and clean results of `p_load`. However sometimes I want to see the warnings of possible conflicts between packages. Is it possible to display all warnings as well? 

Thanks!

**Comment by Dasonk** [comment]
We can look into it.

**Comment by tungmilan** [comment]
Thanks @Dasonk ! This would be very helpful when sharing R scripts with others who are probably not aware of all the possible conflicts

**Comment by sfirke** [comment]
This would be great.  My ideal outcome would be some kind of elegant printed summary that summarizes the warnings, similar to how `library(tidyverse)` yields:
```
Conflicts with tidy packages ---------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
```
But if nothing else, an option to just pass the warnings through as-is would be helpful!
