### ISSUE TITLE
Upload to CRAN (release date)

### ISSUE THREAD

**Issue by trinker** [trinker/pacman#36]
We will release pacman to CRAN on 2-1-2014.  Before then we will:

1. Tackle as many [issues](https://github.com/trinker/pacman/issues?state=open) as possible **TR/DK**
2. ~~Remove the release data info from README.md~~ **TR**
3. ~~Spell check manual~~ **TR**
4. ~~Test all examples~~ **TR**
5. Run CRAN checks on all 3 OS with R 3.0.2 and R dev     
6. ~~Add `\code{}` around `TRUE`, `FALSE` and `NULL` in documentations~~**TR**
7.

**Comment by Dasonk** [comment]
> We obviously pushed back our release date but we've both been working on it for the past couple of  days. I think we could set another deadline. Maybe we should make it cute and have it release on Valentines Day. Then people will LOOOVE it.

Exactly a year later I'm going to make the same suggestion.  Valentines Day.  This time we release it regardless of how much we fix it up before then.  How about it?

**Comment by trinker** [comment]
:+1: thumbsup: and if we don't it's a :facepunch: for us both.
