### ISSUE TITLE
Questions on finalization and utilization 

### ISSUE THREAD

**Issue by MarcoDVisser** [trinker/pacman#60]
1) When will this package be done, finally? ;)

2) Can I use it to remove ggplot from any so inflicted system?

Love,

TE

**Comment by Dasonk** [comment]
The plan is to release on Valentines Day regardless of bug status.  It's usable at the moment. I want to get some stuff cleaned up before release.

You could use it to remove ggplot from an "infected" system! But ggplot is so old.  Is it because you don't have much space on your system and you want to make room for ggplot2?

**Comment by trinker** [comment]
Good point Dason.  Perhaps we need this line in `p_delete`

```r
if (Sys.info()[["user"]] == "MarcoDVisser" && packages == "ggplot2") {
    stop("You are obviously an amateur; `pacman` will protect you from yourself" )
}
```

**Comment by MarcoDVisser** [comment]
I really appreciate you guys releasing it on Valentines day just for me. Usually I only receive flowers from trinker. I feel the love.

**Comment by Dasonk** [comment]
Maybe we should create a branch just for Marco.  I'm thinking we could modify the functions to have the functionality implied by the following pseudocode:

```
p_load <- function(packages){
    load_the_packages(packages)
    if(ggplot2 not in packages){
        print("would you like to load ggplot2?")
        response <- get_response()
        if(response == "y"){
            load(ggplot2)
        }else{
            print("you probably mistyped that")
            load(ggplot2)
            print("you probably want some of Hadley's other packages too!")
            load(dplyr, reshape2, tidyr, testthat, httr, pryr, plyr)
            print("Do you need to do profiling? Here you go")
            load(profr)
        }
    }
}
```

**Comment by MarcoDVisser** [comment]
That does go far enough. I mean if you really want to make me hurt then add this:

```
p_load_best <- function(packages){
    load_the_packages(packages)
    if(ggplot2 not in packages){
        print("would you like to load ggplot2?")
        response <- get_response()
        if(response == "y"){
            p_load(ggplot2)
        }else{
            print("you probably mistyped that")
            p_load(ggplot2)
            print("you probably want some of Hadley's other packages too!")
            p_load(dplyr, reshape2, tidyr, testthat, httr, pryr, plyr)
            print("Do you need to do profiling? Here you go")

           if(aprof is in packages){
           p_delete(aprof) 
           print("Where is your mom?. I want her in my bed - Hamid")
          }
          p_load(profr)
        }
    }
}
```

**Comment by Dasonk** [comment]
I like it! Maybe we could go even further...

p_load_best <- function(packages){
    load_the_packages(packages)
    if(ggplot2 not in packages){
        print("would you like to load ggplot2?")
        response <- get_response()
        if(response == "y"){
            p_load(ggplot2)
        }else{
            print("you probably mistyped that")
            p_load(ggplot2)
            print("you probably want some of Hadley's other packages too!")
            p_load(dplyr, reshape2, tidyr, testthat, httr, pryr, plyr)
            print("Do you need to do profiling? Here you go")

           if(aprof is in packages){
           p_delete(aprof) 
           print("Where is your mom?. I want her in my bed - Hamid")
          }
          p_load(profr)
          delete_if_installed_on_system("emacs")
          if_installed("MSWord"){
              make_system_link("emacs -> word")
          }else{
              make_system_link("emacs -> notepad")
              print("for best experience please install MS Office!")
          }
          delete_if_installed_on_system("anything latex related")
          print("much better!")
        }
    }
}

**Comment by trinker** [comment]
You two take wasting time to a new level.  My snarky retort took all of 20 seconds.  You two on the other hand actually put time and effort into stupidity.  :hear_no_evil:

**Comment by MarcoDVisser** [comment]
True stupidity needs effort and hardwork, Tyler.

**Comment by Dasonk** [comment]
I believe this can be closed.  Also - raptors are terrible.
