### ISSUE TITLE
`data` requires specific environment in R dev version (throws NOTE)

### ISSUE THREAD

**Issue by trinker** [trinker/pacman#66]
The following functions throw a note:

``` r
p_data: Error while checking: invalid 'envir' argument
p_functions: Error while checking: invalid 'envir' argument
p_funs: Error while checking: invalid 'envir' argument
```

because `data` has an `envir = .GlobalEnv` argument.  We may have to add and `envir` argument to these 2 functions and then use position as `.GlobalEnv` is not allowed.

**Comment by Dasonk** [comment]
Is this still an issue?

**Comment by trinker** [comment]
unsure that is long ago...I somehow doubt it

**Comment by Dasonk** [comment]
Well if you're not sure about it and I certainly have no idea. I'm going to go ahead and close it and if it seems like it's an issue in the future we can either reopen or make a new issue.
