### ISSUE TITLE
p_load_current_gh fails if devtools is not installed

### ISSUE THREAD

**Issue by sfirke** [trinker/pacman#71]
If I delete devtools and then run `p_load_current_gh("trinker/wakefield")` I get:

> Error in loadNamespace(name) : there is no package called ‘devtools’

Could p_load_current_gh() check to see if devtools is installed, and if not, install it?  I see it loads devtools if not currently loaded, so it's halfway there.

pacman helps the beginners I coach with package loading, since they don't have to install.packages.  But right now I can't have them load GitHub packages so seamlessly.  My current approach is to precede the `p_load_current_gh()` line with `p_load(devtools)` - not a huge problem, but would be smoother without it, and this way they don't need to load devtools unless it is actually needed later for a `p_load_current_gh()` call.

**Comment by trinker** [comment]
This would be masking an installation that CRAN likes to have done as the dependencies when the package is installed.  I think it would be bad practice to have it install on the fly though convenient for a beginner.  

You said:

> I see it loads devtools if not currently loaded, so it's halfway there.

I don't think it does.  I believe we `::` which will not load the package just call a particilar function from the name space.  

My co-author @Dasonk may have other thoughts  but from CRAN's *Writing R Extensions*:

> The ‘Imports’ field should not contain packages which are not imported from (via the NAMESPACE file or :: or ::: operators), as all the packages listed in that field need to be installed for the current package to be installed. (This is checked by R CMD check.)

> R code in the package should call library or require only exceptionally. Such calls are never needed for packages listed in ‘Depends’ as they will already be on the search path. It used to be common practice to use require calls for packages listed in ‘Suggests’ in functions which used their functionality, but nowadays it is better to access such functionality via :: calls

**Comment by trinker** [comment]
@Dasonk  maybe a warning in `p_delete` if **devtools** is deleted that some functionality of **pacman** may not work?

**Comment by sfirke** [comment]
Ah, it didn't occur to me that if I'd tested it all from scratch (re-deleting pacman, too) - the normal use case for a new pacman user - it would install devtools when pacman installs.  Doing that, I see it works perfectly.  This is a non-issue, then.  Thanks!
