### ISSUE TITLE
Documentation doesn't differentiate p_load_current_gh and p_load_gh

### ISSUE THREAD

**Issue by sfirke** [trinker/pacman#72]
I spent a while trying to figure out which I need, and what the difference is, because the documentation description is identical for both functions:

> This function is a wrapper for install_github and require. It checks to see if a package is
> installed, if not it attempts to install the package from GitHub.

It looks like `p_load_current_gh` force-installs, which is what I want, so I went with that.  But the "current" in the function name didn't help me figure it out.  Could you make it clearer in the documentation what the difference is?

**Comment by trinker** [comment]
Thanks for the feedback.  I agree.  I added a line that I believe should make it clearer.  Feel free to reopen if this still isn't clear.
