### ISSUE TITLE
Getting buzz around pacman

### ISSUE THREAD

**Issue by trinker** [trinker/pacman#8]
I have been wondering if it would be better to (at some point) stop working on pacman in isolation and get some input from others.  

Thoughts for promoting pacman and getting people here to try it out and test it:

You and I both have blogs (these blogs are linked to stats blogs and mine is linked to R bloggers).  By simple putting out a small mess around tutorial as a blog we'll begin to reach people to come test and provide feedback, ideas, requests and issues.

I also put a page for pacman on my blog: [LINK](http://trinkerrstuff.wordpress.com/pacman/)

So I guess the questions are:
1) is this something we should do and if so when?
2) any other promotion ideas

**Comment by Dasonk** [comment]
We could make a post at TS as well.  I don't have a problem with this type of advertising at TS as long as it's from members that have been around for more than two days.  I guess I could ask quark for permission to make sure there isn't an issue with it being 'spammy'.  We could also go back and bump questions/answers that mention pacman by editing in that we can install from CRAN now.

**Comment by trinker** [comment]
As long as quark is cool with it but I don't want to do something he'd not like.

**Comment by trinker** [comment]
I updated the stack questions I saw.

**Comment by Dasonk** [comment]
We're on CRAN now so should we close this issue?

**Comment by Dasonk** [comment]
We've released to CRAN.  I think we can handle the buzz more organically or open a different issue if needed.
