### ISSUE TITLE
Primary language detected as html

### ISSUE THREAD

**Issue by Dasonk** [trinker/pacman#85]
Due to the staticdocs the primary language that github declares this repository to be is... HTML.

We can correct this by treating the generated help pages as 'vendored'. Check the .gitattributes section here:
https://github.com/github/linguist

**Comment by Dasonk** [comment]
Commit d91e9a6ac72b38d3407feb6c7161a935ae2ae298 fixes the issue

**Comment by trinker** [comment]
Cool didn't know you could do this

**Comment by Dasonk** [comment]
I ended up listing the html as "documentation" which doesn't get counted either instead of listing it as "vendored". It's more accurate in my opinion although it doesn't really matter in practice at least in terms of deciding whether the files get included in the language stats.
