### ISSUE TITLE
Port travis over to native

### ISSUE THREAD

**Issue by Dasonk** [trinker/pacman#88]
travis now has native support for R.

https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

That should make it cleaner and easier to maintain.

**Comment by Dasonk** [comment]
This actually is pretty nice because we can have it automatically run on old versions, current version, dev version AND have it do all of that for linux AND osx.  Let me know what you think but my travis file in docstring takes care of all of that.

https://github.com/Dasonk/docstring/blob/master/.travis.yml

**Comment by trinker** [comment]
Go right ahead.  I switched over to other packages 6 months ago.  But haven't tried all the fancy things you're describing.

**Comment by Dasonk** [comment]
What do you mean by "I switched over to other packages 6 months ago"?

**Comment by trinker** [comment]
Sorry not clear.  Started using native R in travis in my other packages: e.g., https://github.com/trinker/textclean/blob/master/.travis.yml

**Comment by Dasonk** [comment]
Gotcha.  And the fancy things are pretty simple to implement (just those changes to the .yml) but it adds multiple build systems.  Which means multiple places the build can fail but it's good to know if it's going to fail somewhere.

**Comment by trinker** [comment]
May need to be tweaked a bit

**Comment by Dasonk** [comment]
Just like your face.

Although it looks good to me. Unlike your face.

If I was any more professional on this site I might explode.

**Comment by trinker** [comment]
Well said
