### ISSUE TITLE
error in readRDS on R 3.4.0

### ISSUE THREAD

**Issue by arbelt** [trinker/pacman#90]
Not entirely sure what the issue is, but I recently upgraded R to 3.4.0 and ever since pacman seems to be causing issues.  If I `p_load` or `p_install` a package not already installed, I end up with an error message about readRDS:

```
Error in readRDS(dest) : error reading from connection
```

`install.packages` at this point will return the same error.  However, if I restart R and do _not_ load pacman then `install.packages` works just fine...

**Comment by Dasonk** [comment]
Yikes. Seems like a serious issue.  Just to make sure I have the details correct... are you attempting to install a package you don't currently have and are trying to install from CRAN?

**Comment by Dasonk** [comment]
I can't reproduce the issue on Windows 10. Can you give the output from sessionInfo() and what package you were trying to install?

**Comment by Dasonk** [comment]
@trinker I was able to reproduce the issue sporadically.  I think the easter egg needs to go.

**Comment by arbelt** [comment]
Here's `sessionInfo()`.  My `.Rprofile` is pretty minimal, just a `require(utils)` and a snippet for `pacman`.  It's been sporadic, but it seems to "trigger" most often when I `p_load` something that's not installed, and once it appears later calls to `install.package` show the same error.

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices datasets  utils     base     

other attached packages:
[1] lintr_1.0.0  pacman_0.4.4

loaded via a namespace (and not attached):
[1] compiler_3.4.0 lazyeval_0.2.0 magrittr_1.5   rex_1.1.1     
```

**Comment by Dasonk** [comment]
I think commit c8893181efac851058377efa8fc28a0b189809d7 should fix the issue.  Can you install the latest version and report back on if the issue seems to be fixed?

**Comment by arbelt** [comment]
No go... just tried with `p_load(plotly)`:

```
Installing package into ‘/Users/azw803/Library/R/3.4/library’
(as ‘lib’ is unspecified)
also installing the dependencies ‘viridisLite’, ‘hexbin’, ‘crosstalk’

Error in readRDS(dest) : error reading from connection
```

**Comment by arbelt** [comment]
So I tracked down the issue: `install.packages` emits a warning when `PACKAGES.rds` is not found on the CRAN repo:

```
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
```

`install.packages` installs just fine after that, but `p_install` is catching the warning and passing off to BioC.  I'm still a bit concerned that a failed `p_install` seems to cause future `install.packages` to fail though.

Made a simple PR #91 that fixes this particular issue, but it is admittedly without reading much of the package code, so perhaps something more needs to be done.

**Comment by arbelt** [comment]
Okay, I think this is figured out... updated the #91 and added a longer note there.  Short version: catching the warning prevented cleanup in `available.packages` from happening, leaving an invalid "cache".  This probably should be handled in `available.packages`, but isn't.  So I modified the code a bit not to unwind the stack and let `install.packages` finish before trying BioC.
