### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by Dasonk** [trinker/pacman#96]
Since the repo is under your username I can't add topics (at least as far as I can tell).  It wouldn't hurt to add some topics like I have in [docstring](https://github.com/Dasonk/docstring) to help people find the repo.

**Comment by trinker** [comment]
Added some, any others? Delete any? Closing for now.  Re-open if you want changes/additions.

**Comment by Dasonk** [comment]
Maybe [r-package], [cran], [github]?

**Comment by trinker** [comment]
done
